name: release_textmod_php_sdk

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Select the version to publish'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      branch:
        description: 'Select the branch to run the workflow'
        required: true
        default: 'php8'
        type: string

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Determine next version
        id: version
        run: |
          nextVersion=$(php .github/scripts/determine_version.php "${{ github.event.inputs.version }}")
          echo "VERSION=${nextVersion}" >> $GITHUB_ENV

      - name: Create tag
        run: |
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}
