name: release_textmod_php_sdk

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Select the version to publish'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      branch:
        description: 'Select the branch to run the workflow'
        required: true
        default: 'php8'
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - '8.0'
          - '8.1'
          - '8.2'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug # Enable Xdebug for code coverage

      - name: Install Xdebug
        if: startsWith(matrix.php-version, '7.') # Xdebug is not required for PHP 8.x
        run: sudo apt-get install -y php-xdebug

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit tests with coverage
        run: composer test

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Determine next version
        id: version
        run: |
          nextVersion=$(php .github/scripts/determine_version.php "${{ github.event.inputs.version }}")
          echo "VERSION=${nextVersion}" >> $GITHUB_ENV

      - name: Create tag
        run: |
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}
